### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by hemantborole** [kazuhisya/dia-aws-simple-icons#1]
make: convert: Command not found
makefile:102: recipe for target '************/dia-aws-simple-icons/.outputs/shapes/AWS_Simple_Icons_Compute_and_Networking_Amazon_EMR--.png' failed

Looking at makefile, I see 
  ./convert -density 600 -resize 22x22 $(<) $(@)

I changed that to 
./convert.rb -density 600 -resize 22x22 $(<) $(@)

Now that fails with 
./convert.rb:5:in `initialize'./convert.rb:5:in`initialize': No such file or directory @ rb_sysopen - -density (Errno::ENOENT)
        from ./convert.rb:5:in `new'
        from ./convert.rb:5:in`<main>'

Sounds like a case of some missing gem. Sounds like some missing gem?
I tried gem install convert and there isnt one.

**Comment by hemantborole** [comment]
Nevermind ,missing imagemagick. Installed it and the build went through.

**Comment by kazuhisya** [comment]
Thank you for using this.
And then, this issue is closed.
